---
spiral_lc_system:
  ros__parameters:
    type: system
    parts:
      spiral_lc_node
    modes:
      __DEFAULT__:
        spiral_lc_node: active.__DEFAULT__
      FAST:
        spiral_lc_node: active.FAST
      SLOW:
        spiral_lc_node: active.SLOW
      DEACTIVATED:
        spiral_lc_node: inactive.SLOW

spiral_lc_node:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          spiral_width: 1.0
          spiral_altitude: 1.0
      FAST:
        ros__parameters:
          spiral_width: 1.0
          spiral_altitude: 2.0
      SLOW:
        ros__parameters:
          spiral_width: 1.0
          spiral_altitude: 0.5

follow_pipeline_system:
  ros__parameters:
    type: system
    parts:
      follow_pipeline_lc
    modes:
      __DEFAULT__:
        follow_pipeline_lc: inactive
      ON:
        follow_pipeline_lc: active
      OFF:
        follow_pipeline_lc: inactive

follow_pipeline_lc:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          random_param: 2.0

thruster:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          thruster1: 1
          thruster2: 1
          thruster3: 1
          thruster4: 1
          thruster5: 1
          thruster6: 1
      TF1:
        ros__parameters:
          thruster1: 0
          thruster2: 1
          thruster3: 1
          thruster4: 1
          thruster5: 1
          thruster6: 1
      TF2:
        ros__parameters:
          thruster1: 1
          thruster2: 0
          thruster3: 1
          thruster4: 1
          thruster5: 1
          thruster6: 1
      TF3:
        ros__parameters:
          thruster1: 1
          thruster2: 1
          thruster3: 0
          thruster4: 1
          thruster5: 1
          thruster6: 1
      TF4:
        ros__parameters:
          thruster1: 1
          thruster2: 1
          thruster3: 1
          thruster4: 0
          thruster5: 1
          thruster6: 1
      TF5:
        ros__parameters:
          thruster1: 1
          thruster2: 1
          thruster3: 1
          thruster4: 1
          thruster5: 0
          thruster6: 1
      TF6:
        rot__parameters:
          thruster1: 1
          thruster2: 1
          thruster3: 1
          thruster4: 1
          thruster5: 1
          thruster6: 0
