name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_docker:
    name: Build suave pkg
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build pkg
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: suave
          target-ros2-distro: humble
          vcs-repo-file-url: https://raw.githubusercontent.com/kas-lab/suave/main/suave/suave.rosinstall
